version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: book_user
      POSTGRES_PASSWORD: book_password
      POSTGRES_DB: book_recommendation
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - book_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - book_network

volumes:
  pgdata:

networks:
  book_network: